### ISSUE TITLE
Does not run on fresh install

### ISSUE THREAD

**Issue by nathanheffley** [austinkregel/atom-ui#1]
Hello! I was attempting to check out this project and see what it does, but the steps in the README do not work.

Following them directly gets a 404 from the NPM registry when trying to run `npx start-storybook` because `start-storybook` does not exist in the registry.

I can get around that by install `@storybook/react` which then attempts to build the project, but fails horribly. It keeps wanting me to install more and more React packages, as it appears React is not even installed in `package.json` even though it is used in the source code.

**Comment by nathanheffley** [comment]
I don't have Storybook CLI installed on my machine, nor any kind of React CLI, so if you have either of those installed and it works for you, that could be it 🤔

**Comment by austinkregel** [comment]
🤔 I'll look into this right away! 👀

**Comment by austinkregel** [comment]
~~This should be fixed with this commit https://github.com/austinkregel/atom-ui/commit/946b9c04d58a43fd394a9c0aa429043c5c442a9f~~

Correction: It should be fixed with this commit https://github.com/austinkregel/atom-ui/commit/67d5625923495bdbd9f05b86a42c5d0c5fc3cf16, I didn't realize my sandbox had some tools installed globally so they weren't being added to the Package.json file
